server:
  port: 8080

swagger:
  title: Rental Service API
  description: Library rental service API
  version: v1.0.0
  contact:
    name: Library Team
    email: support@example.com

spring:
  application:
    name: rental-service
  datasource:
    url: jdbc:mariadb://localhost:3306/rental_db
    username: library
    password: library
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: rental
      max-poll-records: 10
    properties:
      schema.registry.url: http://localhost:8085
  data:
    redis:
      host: localhost
      port: 6379

app:
  kafka:
    consumer:
      processing:
        ttl: 10m
    topics:
      rental-rent: rental_rent
      rental-return: rental_return
      overdue-clear: overdue_clear
      rental-result: rental_result
      point-use: point_use
      rent-cancel: rent_cancel
      return-cancel: return_cancel
      overdue-clear-cancel: overdue_clear_cancel
