server:
  port: 8084

spring:
  application:
    name: bestbook-service
  datasource:
    url: jdbc:mariadb://localhost:3306/bestbook_db
    username: library
    password: library
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bestbook
  data:
    redis:
      host: localhost
      port: 6379

app:
  kafka:
    topics:
      rental-rent: rental_rent
